language: python

matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.6-dev" # 3.6 development branch
    - os: linux
      python: "3.7-dev" # 3.7 development branch
    - os: linux
      python: "nightly"

install: pip install -r requirements.txt

script:
 - coverage run --source . -m pytest
 - coverage report